export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const REGISTRATION_ERRORS = 'REGISTRATION_ERRORS';

export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const AUTHENTICATION_SUCCESS_ERRORS = 'AUTHENTICATION_SUCCESS_ERRORS';

export const RESTART_USER_REQUEST = 'RESTART_USER_REQUEST';
export const RESTART_USER_SUCCESS = 'RESTART_USER_SUCCESS';
export const RESTART_USER_FAILURE = 'RESTART_USER_FAILURE';

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
